# Generated by Django 5.2.3 on 2025-06-13 22:20

import crossword.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crossword.models.generate_code, max_length=8, unique=True)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('hint', models.TextField()),
                ('direction', models.CharField(choices=[('across', 'Across'), ('down', 'Down')], max_length=10)),
                ('start_row', models.IntegerField()),
                ('start_col', models.IntegerField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='crossword.crosswordpuzzle')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='crossword.crosswordpuzzle')),
            ],
            options={
                'unique_together': {('puzzle', 'display_name')},
            },
        ),
    ]
