# Generated by Django 5.2.3 on 2025-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
