# Generated by Django 5.2.3 on 2025-06-15 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0002_crosswordpuzzle_duration_crosswordpuzzle_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct_words',
            field=models.ManyToManyField(blank=True, related_name='solved_by', to='crossword.word'),
        ),
        migrations.AlterField(
            model_name='crosswordpuzzle',
            name='cols',
            field=models.IntegerField(help_text='Number of columns (max 50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='crosswordpuzzle',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes (between 5 and 120)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='crosswordpuzzle',
            name='rows',
            field=models.IntegerField(help_text='Number of rows (max 50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Display name can only contain letters, numbers, spaces, and hyphens', regex='^[\\w\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='word',
            name='hint',
            field=models.TextField(help_text='Hint for the word (max 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Word must contain only letters', regex='^[A-Za-z]+$')]),
        ),
    ]
