# Generated by Django 5.2.3 on 2025-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0004_solvedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordpuzzle',
            name='waiting_room_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
