# Generated by Django 4.2.14 on 2025-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0005_crosswordpuzzle_waiting_room_start_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['puzzle', 'is_active', '-points'], name='crossword_p_puzzle__95fd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['puzzle', '-points', 'joined_at'], name='crossword_p_puzzle__d2e1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-points', 'joined_at'], name='crossword_p_points_42acb4_idx'),
        ),
        migrations.AddIndex(
            model_name='solvedword',
            index=models.Index(fields=['solved_by', '-solved_at'], name='crossword_s_solved__3255bb_idx'),
        ),
        migrations.AddIndex(
            model_name='solvedword',
            index=models.Index(fields=['puzzle', '-solved_at'], name='crossword_s_puzzle__ec3e14_idx'),
        ),
    ]
