# Generated by Django 4.2.14 on 2025-08-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solvedword',
            unique_together={('puzzle', 'word', 'solved_by')},
        ),
    ]
