# Generated by Django 4.2.14 on 2025-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0007_allow_multiple_solvers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='crossword_p_puzzle__95fd4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='crossword_p_puzzle__d2e1d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='crossword_p_points_42acb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='solvedword',
            name='crossword_s_solved__3255bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='solvedword',
            name='crossword_s_puzzle__ec3e14_idx',
        ),
        migrations.AlterUniqueTogether(
            name='solvedword',
            unique_together={('puzzle', 'word')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['puzzle', 'is_active', '-points', 'joined_at'], name='player_leaderboard_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['puzzle', 'is_active'], name='player_active_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-points'], name='player_points_idx'),
        ),
    ]
