# Generated by Django 4.2.14 on 2025-08-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0008_remove_player_crossword_p_puzzle__95fd4c_idx_and_more'),
    ]

    operations = [
    ]
